# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Breach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_given_name', models.CharField(db_column='PersonGivenName', max_length=35, null=True)),
                ('person_family_name', models.CharField(db_column='PersonFamilyName', max_length=35, null=True)),
                ('person_stated_gender', models.CharField(db_column='PersonStatedGender', max_length=1, null=True)),
                ('person_birth_date', models.IntegerField(db_column='PersonBirthDate', null=True)),
                ('person_age_at_attendance', models.IntegerField(db_column='PersonAgeAtAttendance', null=True)),
                ('person_global_number', models.CharField(db_column='PersonGlobalNumber', max_length=10, null=True)),
                ('person_global_number_status_indicator', models.CharField(db_column='PersonGlobalNumberStatusIndicator', max_length=2, null=True)),
                ('person_identity_withheld_reason', models.CharField(db_column='PersonIdentityWithheldReason', max_length=2, null=True)),
                ('person_local_number', models.CharField(db_column='PersonLocalNumber', max_length=20, null=True)),
                ('person_usual_address_1', models.CharField(db_column='PersonUsualAddress1', max_length=35, null=True)),
                ('person_usual_address_2', models.CharField(db_column='PersonUsualAddress2', max_length=35, null=True)),
                ('person_usual_address_postcode', models.CharField(db_column='PersonUsualAddressPostcode', max_length=10, null=True)),
                ('person_residence_org_code', models.CharField(db_column='PersonResidenceOrgCode', max_length=10, null=True)),
                ('person_usual_residence_type', models.CharField(db_column='PersonUsualResidenceType', max_length=18, null=True)),
                ('person_residence_lsoa', models.CharField(db_column='PersonResidenceLsoa', max_length=10, null=True)),
                ('person_preferred_contact', models.CharField(db_column='PersonPreferredContact', max_length=255, null=True)),
                ('person_gp_practice_code', models.CharField(db_column='PersonGpPracticeCode', max_length=6, null=True)),
                ('person_comm_lang', models.CharField(db_column='PersonCommLang', max_length=18, null=True)),
                ('person_interpreter_rqd', models.CharField(db_column='PersonInterpreterRqd', max_length=18, null=True)),
                ('person_interpreter_lang', models.CharField(db_column='PersonInterpreterLang', max_length=18, null=True)),
                ('person_ethnic_category', models.CharField(db_column='PersonEthnicCategory', max_length=2, null=True)),
                ('person_school', models.CharField(db_column='PersonSchool', max_length=10, null=True)),
                ('person_companion', models.CharField(db_column='PersonCompanion', max_length=255, null=True)),
                ('person_special_patient_note_local', models.CharField(db_column='PersonSpecialPatientNoteLocal', max_length=4096, null=True)),
                ('person_additional_information', models.CharField(db_column='PersonAdditionalInformation', max_length=4096, null=True)),
                ('person_allergies_adverse_reaction', models.CharField(db_column='PersonAllergiesAdverseReaction', max_length=4096, null=True)),
                ('person_comorbidities', models.CharField(db_column='PersonComorbidities', max_length=4096, null=True)),
                ('person_current_meds', models.CharField(db_column='PersonCurrentMeds', max_length=4096, null=True)),
                ('em_care_provider_org_code', models.CharField(db_column='EmCareProviderOrgCode', max_length=9, null=True)),
                ('em_care_provider_site_code', models.CharField(db_column='EmCareProviderSiteCode', max_length=9, null=True)),
                ('em_care_provider_site_type', models.CharField(db_column='EmCareProviderSiteType', max_length=1, null=True)),
                ('em_care_unique_id', models.BigIntegerField(db_column='EmCareUniqueId')),
                ('em_care_arrive_transport_mode', models.CharField(db_column='EmCareArriveTransportMode', max_length=2, null=True)),
                ('em_care_amb_unique_id', models.CharField(db_column='EmCareAmbUniqueId', max_length=20, null=True)),
                ('em_care_arrive_date_time', models.DateTimeField(db_column='EmCareArriveDateTime', null=True)),
                ('em_care_attendance_type', models.CharField(db_column='EmCareAttendanceType', max_length=2, null=True)),
                ('em_care_referral_source', models.CharField(db_column='EmCareReferralSource', max_length=2, null=True)),
                ('em_care_arrive_transfer_source', models.CharField(db_column='EmCareArriveTransferSource', max_length=9, null=True)),
                ('em_care_assess_date_time', models.DateTimeField(db_column='EmCareAssessDateTime', null=True)),
                ('em_care_clinicians', models.CharField(db_column='EmCareClinicians', max_length=4096, null=True)),
                ('em_care_referred_service', models.CharField(db_column='EmCareReferredService', max_length=4096, null=True)),
                ('em_care_dta_date_time', models.DateTimeField(db_column='EmCareDtaDateTime', null=True)),
                ('em_care_complete_date_time', models.DateTimeField(db_column='EmCareCompleteDateTime', null=True)),
                ('em_care_depart_date_time', models.DateTimeField(db_column='EmCareDepartDateTime', null=True)),
                ('em_care_admit_speciality', models.CharField(db_column='EmCareSpeciality', max_length=18, null=True)),
                ('em_care_assessment', models.CharField(db_column='EmCareAssessment', max_length=512, null=True)),
                ('em_care_chief_complaint', models.CharField(db_column='EmCareChiefComplaint', max_length=18, null=True)),
                ('em_care_clinical_narrative', models.CharField(db_column='EmCareClinicalNarrative', max_length=4096, null=True)),
                ('em_care_diagnosis', models.CharField(db_column='EmCareDiagnosis', max_length=4096, null=True)),
                ('em_care_investigations', models.CharField(db_column='EmCareInvestigations', max_length=4096, null=True)),
                ('em_care_treatments', models.CharField(db_column='EmCareTreatments', max_length=4096, null=True)),
                ('em_care_research', models.CharField(db_column='EmCareResearch', max_length=4096, null=True)),
                ('em_care_inj_date_time', models.DateTimeField(db_column='EmCareInjDateTime', null=True)),
                ('em_care_inj_place_lat_long', models.CharField(db_column='EmCareInjPlaceLatLong', max_length=50, null=True)),
                ('em_care_inj_place_exact', models.CharField(db_column='EmCareInjPlaceExact', max_length=255, null=True)),
                ('em_care_inj_place_type', models.CharField(db_column='EmCareInjPlaceType', max_length=2, null=True)),
                ('em_care_inj_activity_type', models.CharField(db_column='EmCareInjActivityType', max_length=18, null=True)),
                ('em_care_inj_activity_detail', models.CharField(db_column='EmCareInjActivityDetail', max_length=18, null=True)),
                ('em_care_inj_mechanism', models.CharField(db_column='EmCareInjMechanism', max_length=18, null=True)),
                ('em_care_inj_drug_alcohol', models.CharField(db_column='EmCareInjDrugAlcohol', max_length=255, null=True)),
                ('em_care_inj_intent', models.CharField(db_column='EmCareInjIntent', max_length=18, null=True)),
                ('em_care_discharge_status', models.CharField(db_column='EmCareDischargeStatus', max_length=2, null=True)),
                ('em_care_discharge_follow_up', models.CharField(db_column='EmCareDischargeFollowUp', max_length=2, null=True)),
                ('em_care_discharge_medication', models.CharField(db_column='EmCareDischargeMedication', max_length=4096, null=True)),
                ('em_care_discharge_instructions', models.CharField(db_column='EmCareDischargeInstructions', max_length=4096, null=True)),
                ('em_care_discharge_information_given', models.CharField(db_column='EmCareDischargeInformationGiven', max_length=18, null=True)),
                ('em_care_discharge_safeguarding', models.CharField(db_column='EmCareDischargeSafeguarding', max_length=2, null=True)),
                ('em_care_transfer_destination', models.CharField(db_column='EmCareTransferDestination', max_length=9, null=True)),
                ('action', models.CharField(max_length=255, null=True)),
                ('bed_requested', models.NullBooleanField()),
                ('person_special_patient_note_local_review_due_date', models.DateTimeField(null=True)),
                ('person_special_patient_note_local_review_date', models.DateTimeField(null=True)),
                ('assigned_clinician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sackett.Bed')),
            ],
        ),
        migrations.CreateModel(
            name='Expected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_given_name', models.CharField(db_column='PersonGivenName', max_length=35, null=True)),
                ('person_family_name', models.CharField(db_column='PersonFamilyName', max_length=35, null=True)),
                ('em_care_chief_complaint', models.CharField(db_column='EmCareChiefComplaint', max_length=18, null=True)),
                ('person_stated_gender', models.CharField(db_column='PersonStatedGender', max_length=1, null=True)),
                ('person_age_at_attendance', models.IntegerField(db_column='PersonAgeAtAttendance', null=True)),
                ('removed', models.BooleanField(db_column='Removed')),
                ('linked_episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sackett.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('template', models.CharField(max_length=1024)),
                ('deleted', models.BooleanField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='breach',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sackett.Episode'),
        ),
        migrations.AddField(
            model_name='breach',
            name='logged_in_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bed',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sackett.Zone'),
        ),
    ]
