# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickListData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('group', models.CharField(max_length=64, null=True)),
                ('sort1', models.IntegerField(null=True)),
                ('sort2', models.IntegerField(null=True)),
                ('char1', models.CharField(max_length=256, null=True)),
                ('char2', models.CharField(max_length=256, null=True)),
                ('bool1', models.NullBooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='breach',
            name='added_date_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 27, 15, 1, 29, 96236, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='picklistdata',
            index_together=set([('table_number', 'code'), ('table_number', 'description')]),
        ),
    ]
