# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0002_auto_20160127_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='bed_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
