# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0003_bed_bed_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=16)),
                ('identifier', models.IntegerField()),
            ],
        ),
    ]
