# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 07:38
from __future__ import unicode_literals

from django.db import migrations
import sackett.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0005_auto_20160304_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='em_care_investigations',
            field=sackett.fields.XmlCharField(blank=True, db_column='EmCareInvestigations', max_length=4096, null=True, xml_tags=('INVS', 'INV')),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_treatments',
            field=sackett.fields.XmlCharField(blank=True, db_column='EmCareTreatments', max_length=4096, null=True, xml_tags=('TRMTS', 'TRMT')),
        ),
    ]
