# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 08:03
from __future__ import unicode_literals

from django.db import migrations
import sackett.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0006_auto_20160308_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='em_care_diagnosis',
            field=sackett.fields.XmlTextField(blank=True, db_column='EmCareDiagnosis', null=True, xml_tags=('DIAGS', ('DIAG', {'id': 'CODE', 'index': 'NUM', 'mod': 'MOD'}))),
        ),
    ]
