# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 08:29
from __future__ import unicode_literals

from django.db import migrations
import sackett.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0007_auto_20160308_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='em_care_diagnosis',
            field=sackett.fields.XmlTextField(blank=True, db_column='EmCareDiagnosis', null=True, xml_tags=('DIAGS', ('DIAG', {'code': 'CODE', 'index': 'NUM', 'mod': 'MOD'}))),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_inj_drug_alcohol',
            field=sackett.fields.XmlCharField(blank=True, db_column='EmCareInjDrugAlcohol', max_length=255, null=True, xml_tags=('INJ_DAS', 'INJ_DA')),
        ),
    ]
