# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0008_auto_20160308_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='em_care_inj_activity_detail',
            field=models.CharField(blank=True, db_column='EmCareInjActivityDetail', max_length=255, null=True),
        ),
    ]
