# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0009_auto_20160308_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='early_discharge',
            field=models.NullBooleanField(),
        ),
    ]
