# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 07:00
from __future__ import unicode_literals

from django.db import migrations
import sackett.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0010_episode_early_discharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='person_preferred_contact',
            field=sackett.fields.XmlCharField(blank=True, db_column='PersonPreferredContact', max_length=255, null=True, xml_tags=('CONTACT', {'email': 'EMAIL', 'home': 'HOME', 'mobile': 'MOBILE'})),
        ),
    ]
