# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0011_auto_20160314_0700'),
    ]

    operations = [
        # TODO: dirty hack - remove the field and recreate, instead of using AlterField - otherwise
        # postgresql complains that you can't cast an int to a datetime
        migrations.RemoveField(
            model_name='episode',
            name='person_birth_date',
        ),
        migrations.AddField(
            model_name='episode',
            name='person_birth_date',
            field=models.DateField(blank=True, db_column='PersonBirthDate', null=True),
        ),
        # migrations.AlterField(
        #     model_name='episode',
        #     name='person_birth_date',
        #     field=models.DateField(blank=True, db_column='PersonBirthDate', null=True),
        # ),
    ]
