# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0012_auto_20160314_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='person_age_at_attendance',
            field=models.DecimalField(blank=True, db_column='PersonAgeAtAttendance', decimal_places=2, max_digits=9, null=True),
        ),
    ]
