# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0013_auto_20160315_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='bed_label',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
