# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0014_bed_bed_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='bed_label',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='bed',
            old_name='bed_name',
            new_name='name',
        ),
    ]
