# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 14:20
from __future__ import unicode_literals

from django.db import migrations
import sackett.fields
import sackett.models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0015_auto_20160323_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='person_interpreter_rqd',
            field=sackett.fields.ValueConverterCharField(blank=True, db_column='PersonInterpreterRqd', from_db=sackett.models.person_interpreter_rqd_from_db, max_length=18, null=True, to_db=sackett.models.person_interpreter_rqd_to_db),
        ),
    ]
