# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0017_auto_20160330_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('record_id', models.IntegerField()),
                ('state', models.IntegerField()),
                ('uuid', models.CharField(max_length=36)),
                ('acquired_date_time', models.DateTimeField()),
                ('last_refresh_date_time', models.DateTimeField()),
            ],
        ),
    ]
