# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0018_recordlock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosisdata',
            old_name='diagnosis',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='diagnosisdata',
            name='icd10_code',
        ),
        migrations.RemoveField(
            model_name='diagnosisdata',
            name='snomed_code',
        ),
        migrations.RemoveField(
            model_name='diagnosisdata',
            name='snomed_term',
        ),
        migrations.RemoveField(
            model_name='picklistdata',
            name='char1',
        ),
        migrations.RemoveField(
            model_name='picklistdata',
            name='char2',
        ),
        migrations.AddField(
            model_name='diagnosisdata',
            name='code',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picklistdata',
            name='bool2',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='picklistdata',
            name='bool3',
            field=models.NullBooleanField(),
        ),
    ]
