# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import sackett.fields
import sackett.models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0019_auto_20160404_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='em_care_admit_speciality',
            field=models.CharField(blank=True, db_column='EmCareAdmitSpeciality', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_discharge_information_given',
            field=sackett.fields.ValueConverterCharField(blank=True, db_column='EmCareDischargeInformationGiven', from_db=sackett.models.em_care_discharge_information_given_from_db, max_length=18, null=True, to_db=sackett.models.em_care_discharge_information_given_to_db),
        ),
    ]
