# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0020_auto_20160404_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='em_care_arrive_transport_mode',
            field=models.CharField(blank=True, db_column='EmCareArriveTransportMode', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_attendance_type',
            field=models.CharField(blank=True, db_column='EmCareAttendanceType', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_discharge_follow_up',
            field=models.CharField(blank=True, db_column='EmCareDischargeFollowUp', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_discharge_safeguarding',
            field=models.CharField(blank=True, db_column='EmCareDischargeSafeguarding', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_discharge_status',
            field=models.CharField(blank=True, db_column='EmCareDischargeStatus', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_inj_place_type',
            field=models.CharField(blank=True, db_column='EmCareInjPlaceType', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_referral_source',
            field=models.CharField(blank=True, db_column='EmCareReferralSource', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='person_stated_gender',
            field=models.CharField(blank=True, db_column='PersonStatedGender', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='expected',
            name='person_stated_gender',
            field=models.CharField(blank=True, db_column='PersonStatedGender', max_length=18, null=True),
        ),
    ]
