# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0021_auto_20160404_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='em_care_arrive_transport_mode',
            field=models.CharField(blank=True, db_column='EmCareArriveTransportMode', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_discharge_safeguarding',
            field=models.CharField(blank=True, db_column='EmCareDischargeSafeguarding', max_length=18, null=True),
        ),
    ]
