# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0022_auto_20160404_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='summary_template',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
