# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0023_zone_summary_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='em_care_attendance_type',
            field=models.CharField(blank=True, db_column='EmCareAttendanceType', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_discharge_follow_up',
            field=models.CharField(blank=True, db_column='EmCareDischargeFollowUp', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_discharge_status',
            field=models.CharField(blank=True, db_column='EmCareDischargeStatus', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='em_care_referral_source',
            field=models.CharField(blank=True, db_column='EmCareReferralSource', max_length=18, null=True),
        ),
    ]
