# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0024_auto_20160427_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisdata',
            name='description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='diagnosisdata',
            name='group1',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='diagnosisdata',
            name='group2',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='diagnosisdata',
            name='group3',
            field=models.CharField(max_length=96),
        ),
    ]
