# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-15 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0026_diagnosisdata_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklistdata',
            name='language_code',
            field=models.CharField(default='en-us', max_length=6),
            preserve_default=False,
        ),
    ]
