# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-24 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0027_picklistdata_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_undischarge', 'Can undo patient discharge'), ('can_administer_users', 'Can administer users'), ('can_consult', 'Can be an assigned doctor'), ('can_clear_consultant', 'Can clear assigned doctor for an episode'), ('can_modify_org', 'Can change organisation details'), ('can_administer_zones', 'Can administer hospital zones'), ('can_export_data', 'Can export data'), ('can_review_breaches', 'Can review breach reports'), ('can_view_dashboard', 'Can view dashboard')),
                'managed': False,
            },
        ),
    ]
