# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-04 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sackett', '0028_userpermissionsupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermissionsupport',
            options={'managed': False, 'permissions': (('can_undischarge', 'Can undo patient discharge'), ('can_administer_users', 'Can administer users'), ('can_consult', 'Can be an assigned doctor'), ('can_clear_consultant', 'Can clear assigned doctor for an episode'), ('can_modify_org', 'Can change organisation details'), ('can_administer_zones', 'Can administer hospital zones'), ('can_export_data', 'Can export data'), ('can_review_breaches', 'Can review breach reports'), ('can_view_dashboard', 'Can view dashboard'), ('is_consultant', 'Is a doctor, for the purpose of assignment to episodes'))},
        ),
    ]
