ZONE_WAITING_LIST_BED_NAME = '__zone_waiting_list__'
ZONE_WAITING_LIST_BED_INDEX = -1
ZONE_WAITING_LIST_DRAG_DATA_ID = 'waiting_list'
ZONE_WAITING_LIST_ITEM_DRAG_DATA_PREFIX = 'w_'

RECORD_LOCKING_MAX_LIVE_LOCK_TIME_SECONDS = 10